print("Let's play aMad Libs game! Fill in the blanks:")
favorite_food= input("Faviorte food: ")
Kitchen_item=input("Kitchen item: ")
plural_noun=input("PLural noun: ")
liquid=input("A type of  liquid: ")
adjective1=input("An adjective: ")
spice_or_ingredient=input("An ingredent or spice: ")
adjective2=input("Another adjective: ")
animal=input("An animal: ")
noun=input("A noun: ")
adjective3=input("Another adjective: ")
adjective4=input("One more adjective: ")
family_member=input("A family member: ")
random_object=input("A random object: ")
adjective5=input("An adjective for the dish: ")
adjective6=input("Another adjective: ")
adjective7=input("Final adjective: ")

print(f"One day,I decided to make {favorite_food} for dinner. ")
print(f"First,I grabbed a {Kitchen_item} and started mixing {plural_noun} with some {liquid}.")
print(f"Then,I added a pinch of {adjective1} {spice_or_ingredient} for extra flavor.")
print(f"As I was stirring,my {adjective2} {animal} ran into the kitchen and knocked over the {noun}!")
print(f"It spilled everywhere,making the floor {adjective3} and {adjective4}.")
print(f"I tried to clean it,but suddenly, my {family_member} walked inn and shouted,")
print(f"Why is there {random_object} in the food?!")
print(f"In the end , my {adjective5} dish was a total {adjective6} disaster, but at least it  tasted {adjective7}!")